INSERT INTO veggies (name_et, name_en) VALUES
  ('Tomat', 'Tomato'),
  ('Redis', 'Radish'),
  ('Suvikõrvits', 'Zuccini'),
  ('Kurk', 'Cucumber'),
  ('Kõrvits', 'Pumpkin'),
  ('Kaalikas', 'Rutabaga'),
  ('Peakapsas', 'Cabbage'),
  ('Brokoli', 'Broccoli'),
  ('Lillkapsas', 'Cauliflower'),
  ('Jääsalat', 'Iceberg lettuce'),
  ('Mugulsibul', 'Onion'),
  ('Küüslauk', 'Garlic'),
  ('Porrulauk', 'Leek'),
  ('Karulauk', 'Wild garlic'),
  ('Kartul', 'Potato'),
  ('Baklažaan', 'Eggplant'),
  ('Cayenne', 'Cayenne'),
  ('Jalapeno', 'Jalapeno'),
  ('Peet', 'Beetroot'),
  ('Porgand', 'Carrot'),
  ('Pastinaak', 'Parsnip'),
  ('Aeduba', 'Green bean'),
  ('Põlduba', 'Broad bean'),
  ('Hernes', 'Pea'),
  ('Lääts', 'Lentil'),
  ('Mustrõigas', 'Black radish'),
  ('Varsseller', 'Celery'),
  ('Juurseller', 'Celeriac'),
  ('Fenkol', 'Fennel'),
  ('Rooskapsas', 'Brussels sprout'),
  ('Paprika', 'Paprika'),
  ('Roheline sibul', 'Spring onion'),
  ('Murulauk', 'Chive'),
  ('Spinat', 'Spinach'),
  ('Rukola', 'Rocket'),
  ('Lehtsalat', 'Lettuce'),
  ('Koriander', 'Coriander'),
  ('Bataat', 'Sweet Potato');